# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 봉일균 Portfolio
email: cpt1bong@gmail.com.com
description: > # this means to ignore newlines until "baseurl:"
  CptBong, cpt1bong@gmail.com
# baseurl: "/" # the subpath of your site, e.g. /blog
url: http://localhost:4000
# url: https://prbong.github.io

# twitter_username: jekyllrb
github_username:  cptbong

# Build settings
markdown: kramdown
